- name: Instalaci칩n de Docker y Docker Compose en Ubuntu
  hosts: jenkins
  become: true
  vars:
    jenkins_java_version: "8"

  tasks:
    # Actualizar el cache de paquetes
    - name: Actualizar el cache de paquetes
      apt:
        update_cache: yes

    # Instalar dependencias para Docker
    - name: Instalar dependencias para Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common

    # Agregar la clave GPG oficial de Docker
    - name: Agregar la clave GPG oficial de Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    # Agregar el repositorio de Docker al sources.list.d
    - name: Agregar el repositorio de Docker al sources.list.d
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        state: present

    # Actualizar el cache de paquetes de nuevo (para que encuentre el paquete de Docker)
    - name: Actualizar el cache de paquetes de nuevo (para que encuentre el paquete de Docker)
      apt:
        update_cache: yes

    # Instalar Docker
    - name: Instalar Docker
      apt:
        name: docker-ce
        state: present

    # A침adir el usuario actual al grupo de Docker
    - name: A침adir el usuario actual al grupo de Docker
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    # Instalar Java
    - name: Instalar Java
      apt:
        name: openjdk-{{ jenkins_java_version }}-jdk
        state: present

    - name: Agregar clave del repositorio de Jenkins
      apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io.key
        state: present

    - name: Agregar repositorio de Jenkins
      apt_repository:
        repo: deb https://pkg.jenkins.io/debian-stable binary/
        state: present

    - name: Instalar Jenkins
      apt:
        name: jenkins
        state: present

    # Iniciar Jenkins
    - name: Iniciar Jenkins
      service:
        name: jenkins
        enabled: true
        state: started

    # Instalar Docker Compose
    #- name: Instalar Docker Compose
    #  shell: |
    #    curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    #    chmod +x /usr/local/bin/docker-compose
    #  args:
    #    creates: /usr/local/bin/docker-compose

    - name: Establecer vm.max_map_count en el kernel
      sysctl:
        name: vm.max_map_count
        value: "262144"
        state: present
        reload: yes

    #- name: Copiar archivo de configuraci칩n de Nginx
    #  copy:
    #    src: docker-compose.yml
    #    dest: /home/{{ ansible_user }}/docker-compose.yml

    # Ejecutar un archivo docker-compose.yml
    #- name: Ejecutar docker-compose.yml
    #  command: docker-compose up -d
    #  args:
    #    chdir: /home/{{ ansible_user }}/
    #  become_user: "{{ ansible_user }}"
    #  become_method: su

    - name: Instalar plugins jenkins
      command: jenkins-plugin-cli --plugin-file /plugins.txt
      become_user: "{{ ansible_user }}"
      become_method: su
      notify: restart jenkins

  #handlers:
  #  - name: restart jenkins
  #    command: sudo docker restart jenkins
  #    become_user: "{{ ansible_user }}"
  #    become_method: su
